### PR TITLE
Created an installer for Windows using Inno Setup.

### PR DESCRIPTION
**Pull request by jacgoudsmit**
The flexgui.iss file can be used with Inno Setup 6.0.3, which is an open-source installer generator (see http://www.jrsoftware.org/isinfo.php for more information).

First, you have to do "make zip" to create the flexgui directory with all the files in it that are needed to create the installer. Alternatively, if you can't (or don't want to) build FlexGUI from scratch, you can unzip the zip file from the latest release in the top directory of the Github repository; it will restore the same situation as what's used to create that zip file in the first place.

Then, the .iss file can either be loaded into InnoSetup using File-Open, and then compiled and executed from there, or it can be compiled from the command line by using the command:

  "%programfiles(x86)%\Inno Setup 6\iscc.exe" d:\path\to\flexgui.iss

The installer executable will be generated in the same directory as the .iss file. EDIT: With the latest version of this pull request, the installer automatically extracts the version number from the TCL code and uses it as part of the generated install wizard screens and the output file name (e.g. FlexGUISetup-4.3.1.exe)

Something similar to the following can be added to the makefile (I didn't test this; I don't have a working Cygwin/MingW build environment at this time):

ISCC ?= $(PROGRAMFILES(X86))/iscc.exe

winstaller: flexgui.zip
	$(ISCC) winstaller/flexgui.iss

NOTE: The installer puts the binary files and the include files in a directory that is only accessible for administrators. The samples are stored in a directory flexgui under your Documents directory (and aren't deleted on uninstall).

I changed the gui.tcl file to use the $HOME directory to store the configuration file. (EDIT: The latest version of this pull request automatically does this at install time).

I did testing with my own Propeller 1 projects in Spin and it looks like everything is working as expected. I haven't tested with P2 (yet) and I haven't tested any other languages.

### CODE REVIEW

**Comment by totalspectrum** [comment]
Wow, this looks pretty interesting. Thank you for the work! I know some users would like a proper installer like this. Others prefer the "portable application" style of just putting the app + all files into one directory. So if I do adopt this I'll have to support the old installation method too. I'll have to think on this for a bit, I'm not sure what the best way forward is. But I do like the idea of an Inno Setup based installer, thanks!

**Comment by jacgoudsmit** [comment]
You're welcome!

The existing installation method will also still work; in fact the installer is based on the content of the zip file, so it actually _depends_ on the old method, in a way.

I thought the absence of an installer was a matter of you not having time for that yet, but I see that the "unzip a file" installation method has its use too. And obviously for the portable use case, the user will want their config file in the tree where the program is, not in the home directory where I moved it. I don't know enough about Tcl/Tk to do this myself, but perhaps the code can be changed to try to read and write the config file in $ROOTDIR first, and if that doesn't work, read/write it in $::env(HOME) ? That way it's compatible with both use-cases: portable and non-portable.

Another minor problem with the installer is that the version number is hard-coded. Innosetup can extract the version number from the version resource of an .exe file but it can also use the environment to set a version. At work, I use a version.h file that has a number of #defines in it for things like the version number and the copyright year. That single file gets included in the C/C++ source code, and also in .rc files (to generate version resources) and by InnoSetup, for use in the installer. That way when the version changes, you only have to remember to change it in once place. I could probably accomplish this for FlexGUI too, but I couldn't figure out how to set up my system to build it. The include directory structure of Tcl/tk 8.6 in the latest Cygwin64 is apparently very different from the 8.7 or 9.0 that you apparently have in your home directory, and that the makefile expects.

**Comment by jacgoudsmit** [comment]
I made a few changes to the installer code. It now automatically generates the version number from the version.tcl file, and it automatically makes the modification to the gui.tcl file to save the configuration file to the user's home directory ($::env(HOME)) instead of $ROOTDIR which is read-only after the installation is complete. Just to be clear: the change that I had made in the gui.tcl file before to change the config file location, is no longer in my tree and no longer needed.

Reminder: The installer can be used standalone: Simply unzip the flexgui.zip file into the top directory where the Github project is stored, and load the WindowsInstaller\flexgui.iss file into InnoSetup. Compiling from the command line is also possible; see earlier remarks.

**Comment by jacgoudsmit** [comment]
I re-created this pull request in a different branch because this one was getting very messy.

**Pull request closed without merging**
